#!/bin/sh

#DATE=$(date +'%Y%m%d')
DATE=20210503

ROOTFS=/mnt/clfs/clfs-rootfs-$DATE.tar.xz
[ -d /tmp/rootfs ] && rm -rf /tmp/rootfs
mkdir /tmp/rootfs

BOOTFS=/mnt/clfs/clfs-bootfs-$DATE.tar.xz
[ -d /tmp/bootfs ] && rm -rf /tmp/bootfs
mkdir /tmp/bootfs

KERNEL=zImage
INITRD=initrd.cpio.gz
#DTB=bcm2836-rpi-2-b.dtb
DTB=bcm2837-rpi-3-b.dtb

RAWDISK=hda.img
DISK=hda.qcow2

echo "Creating qemu rootfs disk"
[ ! -f $RAWDISK ] && dd if=/dev/zero of=$RAWDISK bs=1M count=4096

mkfs.ext4 $RAWDISK
mount -o loop $RAWDISK /tmp/rootfs

echo "Extracting rootfs : $ROOTFS"
tar pxf $ROOTFS -C /tmp/rootfs
sync

umount /tmp/rootfs

qemu-img convert -f raw -O qcow2 $RAWDISK $DISK

#echo "Creating initrd image"
#find . -print0 | cpio --null -o --format=newc | gzip -9 > /tmp/$INITRD

echo "Extracting bootfs : $BOOTFS"

tar pxf $BOOTFS -C /tmp/bootfs

echo "Booting virtual machine"
# qemu raspi2b REQUIRES arm-only binaries
#qemu-system-arm \
#	-nographic -no-reboot \
#	-M virt -m 1024 -smp 4 \
#	-kernel /tmp/bootfs/$KERNEL \
#	-append "earlyprintk=serial,ttyS0 loglevel=8 console=ttyAMA0 root=/dev/hda" \
#	-drive file=$DISK,if=none,format=raw,id=rootfs \
#	-device virtio-blk-device,drive=rootfs
#	# doesnt work :(
#	-device virtio-scsi-pci,id=scsi0 \
#	-drive if=none,file=$DISK,format=raw,id=rootfs \
#	-device scsi-hd,drive=rootfs,bus=scsi0.0

qemu-system-arm \
	-nographic -no-reboot \
	-M virt -m 1024 -smp 1 \
	-kernel /tmp/bootfs/$KERNEL \
	-append "earlyprintk=serial,ttyS0 loglevel=8 console=ttyAMA0" \
	-drive file=$DISK,if=none,format=qcow2,id=rootfs \
	-device virtio-blk-device,drive=rootfs

#qemu-system-arm \
#	-nographic -no-reboot \
#	-M raspi2 \
#	-kernel /tmp/bootfs/$KERNEL \
#	-dtb /tmp/bootfs/$DTB \
#	-append "earlyprintk=serial,ttyS0 loglevel=8 console=ttyAMA0 root=/dev/mmcblk0" \
#	-drive file=$RAWDISK,if=none,format=raw,id=rootfs \
#	-device sd-card,drive=rootfs

# qemu internal arm invocation
#qemu-system-arm \
#	-display none -vga none \
#	-chardev socket,id=mon,path=/var/tmp/avo_qemu_sock_y2xg63/qemu-29492-monitor.sock -mon chardev=mon,mode=control \
#	-machine raspi2 \
#	-chardev socket,id=console,path=/var/tmp/avo_qemu_sock_y2xg6349/qemu-29492-console.sock,server=on,wait=off \
#	-serial chardev:console \
#	-kernel /var/tmp/.test_arm_raspi2_uart0/boot/kernel7.img \
#	-dtb /var/tmp/.test_arm_raspi2_uart0/boot/bcm2709-rpi-2-b.dtb \
#	-append printk.time=0 earlycon=pl011,0x3f201000 console=ttyAMA0 root=/dev/mmcblk0p2 rootwait dwc_otg.fiq_fsm_enable=0 \
#	-device usb-kbd

