#!/bin/sh

qemu-img create -f qcow2 hda.qcow2 5G

qemu-system-arm \
	-M virt -m 1024 \
	-kernel installer-vmlinuz \
	-initrd installer-initrd.gz \
	-drive if=none,file=hda.qcow2,format=qcow2,id=hd \
	-device virtio-blk-device,drive=hd \
	-netdev user,id=mynet \
	-device virtio-net-device,netdev=mynet \
	-nographic -no-reboot
